// ---------------------------------------------------------------------------
// missionReplays.ts
//
// Generates a small set of fixed-length demo mission datasets by running the
// SAME deterministic simulation core (engineSimulation.ts) offline, so
// replay data is generated by actual system logic rather than hand-authored
// mock numbers. Because the simulation core has no randomness (only smooth
// sinusoidal "sensor noise" seeded by sim time), each dataset is fully
// reproducible.
// ---------------------------------------------------------------------------

import { emptyFault, newFault, stepSimulation, type SimState } from './engineSimulation';
import type { ActiveFault } from '../types';

export interface MissionReplay {
  id: string;
  title: string;
  description: string;
  durationSeconds: number;
  frames: SimState[];
}

function generate(
  id: string,
  title: string,
  description: string,
  durationSeconds: number,
  cfg: { throttle: number; altitude: number; ambientTemp: number },
  faultAt: (t: number) => ActiveFault,
): MissionReplay {
  const frames: SimState[] = [];
  for (let t = 0; t <= durationSeconds; t += 1) {
    frames.push(stepSimulation(t, cfg, faultAt(t)));
  }
  return { id, title, description, durationSeconds, frames };
}

const MISSION_01 = generate(
  'MISSION_01',
  'MISSION 01 — Healthy Cruise',
  'Standard cruise profile with no faults. Engine remains in the HEALTHY band throughout.',
  90,
  { throttle: 58, altitude: 12000, ambientTemp: 18 },
  () => emptyFault(),
);

const MISSION_02 = generate(
  'MISSION_02',
  'MISSION 02 — High Altitude',
  'High-altitude ISR profile. Thinner air and cooler ambient shift the operating point.',
  90,
  { throttle: 76, altitude: 22000, ambientTemp: -8 },
  () => emptyFault(),
);

const MISSION_03 = generate(
  'MISSION_03',
  'MISSION 03 — Overheating Event',
  'Cruise profile with an overheating fault injected partway through the mission.',
  90,
  { throttle: 64, altitude: 14000, ambientTemp: 22 },
  (t) => (t < 30 ? emptyFault() : newFault('OVERHEATING', 75, undefined)) as ActiveFault,
);
// Fix elapsedSeconds so the fault ramps correctly from its injection point.
for (let i = 0; i < MISSION_03.frames.length; i++) {
  const t = MISSION_03.frames[i].simTimeSeconds;
  if (t >= 30) {
    MISSION_03.frames[i] = stepSimulation(
      t,
      { throttle: 64, altitude: 14000, ambientTemp: 22 },
      { type: 'OVERHEATING', severity: 75, elapsedSeconds: t - 30 },
    );
  }
}

const MISSION_04 = generate(
  'MISSION_04',
  'MISSION 04 — Lubrication Degradation',
  'Endurance profile with a lubrication degradation fault injected partway through.',
  90,
  { throttle: 55, altitude: 10000, ambientTemp: 20 },
  () => emptyFault(),
);
for (let i = 0; i < MISSION_04.frames.length; i++) {
  const t = MISSION_04.frames[i].simTimeSeconds;
  if (t >= 25) {
    MISSION_04.frames[i] = stepSimulation(
      t,
      { throttle: 55, altitude: 10000, ambientTemp: 20 },
      { type: 'LUBRICATION_DEGRADATION', severity: 70, elapsedSeconds: t - 25 },
    );
  }
}

export const MISSION_REPLAYS: MissionReplay[] = [MISSION_01, MISSION_02, MISSION_03, MISSION_04];
