// ---------------------------------------------------------------------------
// mlClassifier.ts
//
// Loads the REAL trained model (scripts/train_model.py → ONNX export) and
// runs inference entirely client-side via ONNX Runtime Web (WASM backend).
// No server, no API call, no internet dependency at runtime — the .onnx
// weights and the ORT WASM binary are both served as static files from
// /public, which matters for the "GCS-integrated, air-gapped" deployment
// story: this has to work with zero network connectivity.
//
// Feature order and class label order are loaded from model_meta.json,
// which is generated by the SAME training script that produced the model —
// so this file never hand-encodes an order that could drift out of sync.
// ---------------------------------------------------------------------------

import * as ort from 'onnxruntime-web/wasm';
import type { EngineTelemetry, FaultType, TwinComparisonSet } from '../types';

// Explicitly point at the self-hosted WASM binary by exact path, rather than
// relying on onnxruntime-web's default same-origin resolution via
// `new URL(..., import.meta.url)`. That default path is what broke under
// Vite's dev server (esbuild's dependency pre-bundling rewrites import.meta.url
// in a way that made the runtime fetch resolve to index.html instead of the
// actual .wasm file). Only the binary is overridden here — the `.mjs` loader
// is JS glue code, and Vite refuses to `import()` anything living in
// /public (public assets are served as raw, untouched files, never run
// through the module pipeline), so the .mjs is deliberately left to its
// default bundler-processed resolution rather than pointed at /public too.
ort.env.wasm.wasmPaths = {
  wasm: '/ort/ort-wasm-simd-threaded.wasm',
};
// Force single-threaded WASM: multi-threaded ORT needs cross-origin-isolation
// (COOP/COEP) response headers, which most simple static hosts / a GCS's
// local file server won't set. Single-threaded still runs a 300-tree model
// in low single-digit milliseconds — plenty fast for a 1Hz dashboard tick.
ort.env.wasm.numThreads = 1;

interface ModelMeta {
  featureOrder: string[];
  classLabels: FaultType[];
  modelType: string;
  trainedOn: string;
  testAccuracyClean: number;
}

let sessionPromise: Promise<ort.InferenceSession> | null = null;
let metaPromise: Promise<ModelMeta> | null = null;

function loadSession(): Promise<ort.InferenceSession> {
  if (!sessionPromise) {
    sessionPromise = ort.InferenceSession.create('/models/fault_classifier.onnx', {
      executionProviders: ['wasm'],
      graphOptimizationLevel: 'all',
    });
  }
  return sessionPromise;
}

function loadMeta(): Promise<ModelMeta> {
  if (!metaPromise) {
    metaPromise = fetch('/models/model_meta.json').then((r) => r.json());
  }
  return metaPromise;
}

/** Kicks off loading the model + metadata as early as possible (call once on app start). */
export function preloadModel(): void {
  loadSession().catch(() => {
    /* surfaced via classify()'s own error handling on first real call */
  });
  loadMeta().catch(() => {});
}

export interface ClassifyInput {
  telemetry: EngineTelemetry;
  twin: TwinComparisonSet;
  twinSyncPercent: number;
}

export interface ClassifyResult {
  faultType: FaultType;
  confidence: number; // 0-100
  probabilities: Partial<Record<FaultType, number>>;
  modelInfo: { trainedOn: string; testAccuracy: number };
}

/** Builds the exact 16-feature vector the model was trained on, in the exact
 * order model_meta.json specifies — this indirection is what keeps browser
 * inference from silently drifting out of sync with the training script. */
function buildFeatureVector(input: ClassifyInput, featureOrder: string[]): Float32Array {
  const { telemetry: t, twin } = input;
  const lookup: Record<string, number> = {
    rpm: t.rpm,
    egt: t.egt,
    cht: t.cht,
    oil_pressure: t.oilPressure,
    oil_temperature: t.oilTemperature,
    fuel_flow: t.fuelFlow,
    vibration: t.vibration,
    throttle_cmd: t.throttle,
    altitude_ft: t.altitude,
    ambient_temp_c: 0, // overridden by caller via input below when available
    residual_rpm: twin.rpm.residual,
    residual_egt: twin.egt.residual,
    residual_cht: twin.cht.residual,
    residual_oil_pressure: twin.oilPressure.residual,
    residual_vibration: twin.vibration.residual,
    twin_sync_pct: input.twinSyncPercent,
  };
  return Float32Array.from(featureOrder.map((f) => lookup[f] ?? 0));
}

/**
 * Runs the real trained model against the current telemetry snapshot.
 * Safe to call every simulation tick — a single 300-tree forward pass on the
 * WASM backend takes low single-digit milliseconds.
 */
export async function classifyFault(input: ClassifyInput & { ambientTempC: number }): Promise<ClassifyResult> {
  const [session, meta] = await Promise.all([loadSession(), loadMeta()]);

  const vector = buildFeatureVector(input, meta.featureOrder);
  // ambient_temp_c isn't on EngineTelemetry (it's a SimConfig field), so it's
  // patched in directly at the known index rather than threading it through
  // the whole telemetry type just for this one feature.
  const ambientIdx = meta.featureOrder.indexOf('ambient_temp_c');
  if (ambientIdx >= 0) vector[ambientIdx] = input.ambientTempC;

  const tensor = new ort.Tensor('float32', vector, [1, meta.featureOrder.length]);
  const output = await session.run({ input: tensor });

  const label = Number(output.label.data[0]);
  const probs = output.probabilities.data as Float32Array;

  const probabilities: Partial<Record<FaultType, number>> = {};
  meta.classLabels.forEach((cls, i) => {
    probabilities[cls] = Math.round(probs[i] * 1000) / 10; // 0-100, 1 decimal
  });

  const faultType = meta.classLabels[label];
  const confidence = probabilities[faultType] ?? 0;

  return {
    faultType,
    confidence,
    probabilities,
    modelInfo: { trainedOn: meta.trainedOn, testAccuracy: meta.testAccuracyClean },
  };
}

/** For CSV-import / batch use: classify many rows without re-loading the
 * session each time (loadSession()/loadMeta() are memoised after first call). */
export async function classifyFaultBatch(
  inputs: (ClassifyInput & { ambientTempC: number })[],
): Promise<ClassifyResult[]> {
  const results: ClassifyResult[] = [];
  for (const input of inputs) {
    // eslint-disable-next-line no-await-in-loop -- intentionally sequential;
    // ORT WASM sessions aren't safe to fan out concurrently in the browser.
    results.push(await classifyFault(input));
  }
  return results;
}
